name: pokemon
description: pokemon
version: 8.1.0+412
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  json_annotation: ^4.6.0
  provider: ^6.0.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.2.0
  json_serializable: 6.3.1
  flutter_lints: 2.0.1